name: test

on: [push, pull_request]

jobs:
  coverage-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install
      - run: npm run build
      - run: npm run test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
